apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssqlserver-deployment
spec:
  selector:
    matchLabels:
      app: mssqlserver
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssqlserver
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssqlserver
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssqlserver
              key: SA_PASSWORD
        volumeMounts:
        - name: mssqlserverdb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqlserverdb
        persistentVolumeClaim:
          claimName: mssqlserver-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssqlserver-service
spec:
  selector:
    app: mssqlserver
  ports:
    - protocol: TCP
      port: 41433
      targetPort: 1433
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mssqlserver
spec:
  selector:
    app: mssqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433